server:
  port: 8080
  error:
    include-message: always     # show reason in error response body

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      format_sql: true
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

api:
  base:
    path: /api